parameters:
#    ornj_archive.example.class: Ornj\Bundle\ArchiveBundle\Example

services:
    ornj_archive.zip:
        class: Ornj\Bundle\ArchiveBundle\Services\CreateZip
        arguments:
            - destination: 'web/uploads'
              overwrite: true